"""Outpost pool: modal-local. Generated by modal-devin -- edit freely, no dependency on modal_devin at deploy time."""

import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request

import modal

CADDY_INSTALL = (
    "curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest "
    "| grep browser_download_url | grep linux_amd64.tar.gz | cut -d '\"' -f 4 "
    "| xargs curl -fsSL -o /tmp/caddy.tar.gz "
    "&& tar -xzf /tmp/caddy.tar.gz -C /usr/local/bin caddy "
    "&& chmod +x /usr/local/bin/caddy "
    "&& rm /tmp/caddy.tar.gz"
)

DEVIN_CLI_INSTALL = (
    # installer auto-runs an interactive `devin setup` (browser OAuth) at the
    # end, which always fails with no TTY during an image build; the binary
    # itself is already installed by that point, so ignore that failure
    "curl -fsSL https://cli.devin.ai/install.sh | bash || true"
)

DEVIN_BIN = "/root/.local/bin/devin"


def base_image() -> modal.Image:
    """git + devin CLI + caddy, nothing session-specific baked in."""
    return (
        modal.Image.debian_slim(python_version="3.12")
        .apt_install("git", "curl", "ca-certificates", "tar")
        .run_commands(DEVIN_CLI_INSTALL)
        .run_commands(f"test -x {DEVIN_BIN}")
        .run_commands(CADDY_INSTALL)
        .run_commands("test -x /usr/local/bin/caddy")
        .run_commands("mkdir -p /root/workspace")
    )


# --- credential-injection sidecar -------------------------------------------
#
# Devin's beta doesn't yet support scoping a service-account token below
# Admin, so whatever token we hand a worker today is likely broader than it
# needs. Devin's own Outposts docs also warn that anything in the worker's
# environment "is inherited by the agent's shell" -- so if the real token
# sits in devin worker start's env, a compromised or prompt-injected session
# could read it. This runs a local Caddy reverse proxy (not mitmproxy --
# mitmproxy's TLS-terminating MITM gets fingerprint-blocked by some edges;
# Caddy makes an ordinary outbound HTTPS connection, no interception) that
# holds the real token and injects it into the Authorization header when
# forwarding to the real Devin API. devin worker start only ever sees a
# throwaway token pointed at the sidecar's localhost URL.

CADDYFILE = """\
{
	admin off
	auto_https off
}

:{port} {
	reverse_proxy {upstream} {
		header_up Host {upstream_hostport}
		header_up Authorization "Bearer {token}"
	}
}
"""

# shaped like a real `cog_...` token in case the CLI does any client-side
# format validation before sending it -- Caddy overwrites it regardless
DUMMY_TOKEN = "cog_sidecarmanaged00000000000000000000000000000000"

SIDECAR_PORT = 8686


def start_sidecar(port: int, upstream_api_url: str, real_token: str) -> subprocess.Popen:
    """Start the Caddy sidecar in the background and block until it's ready."""
    caddyfile_path = "/tmp/devin-sidecar.Caddyfile"
    with open(caddyfile_path, "w") as f:
        f.write(
            CADDYFILE.replace("{port}", str(port))
            .replace("{upstream}", upstream_api_url)
            .replace("{token}", real_token)
        )

    proc = subprocess.Popen(
        ["/usr/local/bin/caddy", "run", "--config", caddyfile_path, "--adapter", "caddyfile"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    health_url = f"http://127.0.0.1:{port}/"
    for _ in range(100):
        if proc.poll() is not None:
            output = proc.stdout.read().decode(errors="replace")
            raise RuntimeError(f"caddy sidecar exited before becoming ready:\n{output}")
        try:
            urllib.request.urlopen(health_url, timeout=1)
            return proc
        except urllib.error.URLError:
            time.sleep(0.1)
        except urllib.error.HTTPError:
            # any HTTP response at all (even 4xx/5xx from upstream) means
            # caddy itself is up and proxying
            return proc
    proc.terminate()
    output = proc.stdout.read(4096).decode(errors="replace")
    raise RuntimeError(f"caddy sidecar did not become ready in time:\n{output}")


def clean_worker_env(base_env: dict, sidecar_port: int) -> dict:
    """Env for the devin worker subprocess: no real token, points at the sidecar."""
    return {
        **base_env,
        "DEVIN_API_URL": f"http://127.0.0.1:{sidecar_port}",
        "DEVIN_OUTPOSTS_TOKEN": DUMMY_TOKEN,
    }


# --- the "master function" ---------------------------------------------------
#
# Follows Devin's documented core flow: poll the fleet API for pending
# sessions, atomically claim one, then run `devin worker start` for it. If
# provisioning fails before the worker starts, release the claim so the
# session returns to the queue immediately; if the whole function dies
# before that (host eviction, etc.), Devin's own claim-deadline expiry is
# the documented fallback -- billing for that window is expected behavior
# per their docs, not a gap we need to engineer around.
#
# poll_and_dispatch is cron-scheduled rather than a `while True` loop: Modal
# re-invokes it fresh every tick, so one tick crashing (e.g. a transient DNS
# failure -- this happened during testing) doesn't kill the whole poller.
# Nothing has to be restarted by hand.

POOL_NAME = "modal-local"
POOL_ID = "outpost_env-c2b537724d234336837b2c817d985904"
API_URL = "https://api.beta.devinenterprise.com"
ACCEPTOR_ID = f"modal-{POOL_NAME}"
POLL_INTERVAL_SECS = 30
SESSION_TIMEOUT_SECS = 1800

app = modal.App(f"outpost-pool-{POOL_NAME}")
secret = modal.Secret.from_name("devin-outposts-token")

image = (
    base_image()
    # add your repos here, e.g.:
    # .run_commands("git clone https://github.com/your-org/your-repo /root/workspace/your-repo")
)


def _api_request(api_url, token, method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(f"{api_url}{path}", data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def _release(api_url, token, session_id):
    _api_request(
        api_url, token, "POST",
        f"/opbeta/outposts/devins/{session_id}/release",
        {"acceptor_id": ACCEPTOR_ID},
    )


@app.function(image=image, secrets=[secret], timeout=SESSION_TIMEOUT_SECS + 60)
def run_session(session_id: str):
    token = os.environ["DEVIN_OUTPOSTS_TOKEN"]

    try:
        sidecar_proc = start_sidecar(SIDECAR_PORT, API_URL, token)
        try:
            base_env = {
                k: os.environ[k]
                for k in ("PATH", "HOME", "USER", "LOGNAME", "TMPDIR", "LANG", "TZ")
                if k in os.environ
            }
            worker_env = clean_worker_env(base_env, SIDECAR_PORT)
            result = subprocess.run(
                [
                    DEVIN_BIN, "worker", "start",
                    "--session", session_id,
                    "--pool", POOL_ID,
                    "--acceptor-id", ACCEPTOR_ID,
                ],
                env=worker_env,
                cwd="/root/workspace",
                timeout=SESSION_TIMEOUT_SECS,
            )
            print(f"[{session_id}] devin worker exited: {result.returncode}")
            if result.returncode != 0:
                _release(API_URL, token, session_id)
                print(f"[{session_id}] released claim after nonzero exit")
        finally:
            sidecar_proc.terminate()
    except Exception as e:
        print(f"[{session_id}] run_session failed: {e}", file=sys.stderr)
        _release(API_URL, token, session_id)
        print(f"[{session_id}] released claim after failure")
        raise


@app.function(image=image, secrets=[secret], schedule=modal.Period(seconds=POLL_INTERVAL_SECS))
def poll_and_dispatch():
    api_url = os.environ.get("DEVIN_API_URL", API_URL)
    token = os.environ["DEVIN_OUTPOSTS_TOKEN"]

    try:
        pending = _api_request(
            api_url, token, "GET", f"/opbeta/outposts/devins?pool={POOL_ID}&phase=pending"
        )
    except urllib.error.URLError as e:
        print(f"poll failed: {e}", file=sys.stderr)
        return

    for item in pending.get("items", []):
        session_id = item["metadata"]["session_id"]
        try:
            claim = _api_request(
                api_url, token, "POST",
                f"/opbeta/outposts/devins/{session_id}/claim",
                {"acceptor_id": ACCEPTOR_ID},
            )
        except urllib.error.HTTPError as e:
            if e.code == 409:
                continue  # someone else claimed it first
            print(f"[{session_id}] claim failed: {e}", file=sys.stderr)
            continue

        deadline = claim.get("status", {}).get("claim_deadline")
        print(f"[{session_id}] claimed, claim_deadline={deadline}, dispatching")
        run_session.spawn(session_id)
