"""Outpost pool: modal-local. Generated by modal-devin -- edit freely, no dependency on modal_devin at deploy time."""

import json
import os
import shlex
import sys
import urllib.error
import urllib.request

import modal

DEVIN_CLI_INSTALL = (
    # installer auto-runs an interactive `devin setup` (browser OAuth) at the
    # end, which always fails with no TTY during an image build; the binary
    # itself is already installed by that point, so ignore that failure
    "curl -fsSL https://cli.devin.ai/install.sh | bash || true"
)

DEVIN_BIN = "/root/.local/bin/devin"

main_image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install("git", "curl", "ca-certificates")
    .run_commands(DEVIN_CLI_INSTALL)
    .run_commands(f"test -x {DEVIN_BIN}")
    .run_commands("mkdir -p /root/workspace")
    # add your repos here, e.g.:
    # .run_commands("git clone https://github.com/your-org/your-repo /root/workspace/your-repo")
)


# --- credential-injection sidecar -------------------------------------------
#
# Devin's beta doesn't yet support scoping a service-account token below
# Admin, so whatever token we hand a worker today is likely broader than it
# needs. Devin's own Outposts docs also warn that anything in the worker's
# environment "is inherited by the agent's shell" -- so if the real token
# sat in devin worker start's own env, a compromised or prompt-injected
# session could read it.
#
# This runs Caddy as a real Modal Sandbox sidecar: a genuinely separate
# container on its own network namespace (not just a second process sharing
# the main container's env), reachable by the main container only as
# `http://caddy:PORT`. The real DEVIN_OUTPOSTS_TOKEN is a secret attached
# only to the sidecar container. Caddy injects it into the Authorization
# header via its own environment-variable substitution -- no Python-side templating of
# the Caddyfile at runtime, and the main container never holds the real
# token, only a throwaway one that never leaves it.
#
# (Caddy, not mitmproxy: mitmproxy's TLS-terminating MITM gets
# fingerprint-blocked by some edges; Caddy makes an ordinary outbound HTTPS
# connection, no interception, so there's nothing to fingerprint.)

CADDYFILE = """\
{
	admin off
	auto_https off
}

:{$SIDECAR_PORT} {
	reverse_proxy {$UPSTREAM_URL} {
		header_up Host {upstream_hostport}
		header_up Authorization "Bearer {$DEVIN_OUTPOSTS_TOKEN}"
	}
}
"""

CADDY_INSTALL = (
    "curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest "
    "| grep browser_download_url | grep linux_amd64.tar.gz | cut -d '\"' -f 4 "
    "| xargs curl -fsSL -o /tmp/caddy.tar.gz "
    "&& tar -xzf /tmp/caddy.tar.gz -C /usr/local/bin caddy "
    "&& chmod +x /usr/local/bin/caddy "
    "&& rm /tmp/caddy.tar.gz"
)

sidecar_image = (
    modal.Image.debian_slim()
    .apt_install("curl", "ca-certificates", "tar")
    .run_commands(CADDY_INSTALL)
    .run_commands("test -x /usr/local/bin/caddy")
    # run_commands() becomes a single Dockerfile RUN line -- a raw multi-line
    # argument breaks the line-based Dockerfile parser, so flatten newlines
    # to \n and reinflate them at build time with `printf %b`
    .run_commands(
        "mkdir -p /etc/caddy && printf '%b' "
        + shlex.quote(CADDYFILE.replace("\n", "\\n"))
        + " > /etc/caddy/Caddyfile"
    )
)

# shaped like a real `cog_...` token in case the CLI does any client-side
# format validation before sending it -- Caddy overwrites it regardless
DUMMY_TOKEN = "cog_sidecarmanaged00000000000000000000000000000000"
SIDECAR_PORT = 8686


# --- the "master function" ---------------------------------------------------
#
# Follows Devin's documented core flow: poll the fleet API for pending
# sessions, atomically claim one, then run `devin worker start` for it. If
# provisioning fails before the worker starts, release the claim so the
# session returns to the queue immediately; if the whole function dies
# before that (host eviction, etc.), Devin's own claim-deadline expiry is
# the documented fallback -- billing for that window is expected behavior
# per their docs, not a gap we need to engineer around.
#
# poll_and_dispatch is cron-scheduled rather than a `while True` loop: Modal
# re-invokes it fresh every tick, so one tick crashing (e.g. a transient DNS
# failure -- this happened during testing) doesn't kill the whole poller.
# Nothing has to be restarted by hand.

POOL_NAME = "modal-local"
POOL_ID = "outpost_env-c2b537724d234336837b2c817d985904"
API_URL = "https://api.beta.devinenterprise.com"
ACCEPTOR_ID = f"modal-{POOL_NAME}"
POLL_INTERVAL_SECS = 30
SESSION_TIMEOUT_SECS = 1800

# plain App(name), not App.lookup: `modal deploy` needs a locally-owned app
# to attach @app.function to. Named images need the opposite -- an app with
# an app_id already assigned -- so that build+publish step runs separately,
# below, via `python3 pools/modal_local.py` rather than as part of deploy.
app = modal.App(f"outpost-pool-{POOL_NAME}")
secret = modal.Secret.from_name("devin-outposts-token")
SIDECAR_IMAGE_NAME = f"outpost-{POOL_NAME}-sidecar-caddy"


def _api_request(api_url, token, method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(f"{api_url}{path}", data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def _release(api_url, token, session_id):
    _api_request(
        api_url, token, "POST",
        f"/opbeta/outposts/devins/{session_id}/release",
        {"acceptor_id": ACCEPTOR_ID},
    )


@app.function(image=main_image, secrets=[secret], timeout=SESSION_TIMEOUT_SECS + 60)
def run_session(session_id: str):
    token = os.environ["DEVIN_OUTPOSTS_TOKEN"]

    sb = modal.Sandbox.create(
        "sleep", "infinity",
        app=app, image=main_image, workdir="/root/workspace", timeout=SESSION_TIMEOUT_SECS,
    )
    try:
        sb._experimental_sidecars.create(
            "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile",
            name="caddy",
            image=modal.Image.from_name(SIDECAR_IMAGE_NAME),
            env={"SIDECAR_PORT": str(SIDECAR_PORT), "UPSTREAM_URL": API_URL},
            secrets=[secret],
        )

        wait_proc = sb.exec(
            "sh", "-c",
            f"for i in $(seq 1 100); do "
            f"curl -sf http://caddy:{SIDECAR_PORT}/ -o /dev/null && exit 0; sleep 0.1; done; exit 1",
        )
        if wait_proc.wait() != 0:
            raise RuntimeError("caddy sidecar did not become ready in time")

        worker_env = {
            "DEVIN_API_URL": f"http://caddy:{SIDECAR_PORT}",
            "DEVIN_OUTPOSTS_TOKEN": DUMMY_TOKEN,
        }
        worker_proc = sb.exec(
            DEVIN_BIN, "worker", "start",
            "--session", session_id,
            "--pool", POOL_ID,
            "--acceptor-id", ACCEPTOR_ID,
            env=worker_env,
        )
        for line in worker_proc.stdout:
            print(f"[{session_id}] {line}", end="")
        returncode = worker_proc.wait()
        print(f"[{session_id}] devin worker exited: {returncode}")
        if returncode != 0:
            _release(API_URL, token, session_id)
            print(f"[{session_id}] released claim after nonzero exit")
    except Exception as e:
        print(f"[{session_id}] run_session failed: {e}", file=sys.stderr)
        _release(API_URL, token, session_id)
        print(f"[{session_id}] released claim after failure")
        raise
    finally:
        sb.terminate()


@app.function(image=main_image, secrets=[secret], schedule=modal.Period(seconds=POLL_INTERVAL_SECS))
def poll_and_dispatch():
    api_url = os.environ.get("DEVIN_API_URL", API_URL)
    token = os.environ["DEVIN_OUTPOSTS_TOKEN"]

    try:
        pending = _api_request(
            api_url, token, "GET", f"/opbeta/outposts/devins?pool={POOL_ID}&phase=pending"
        )
    except urllib.error.URLError as e:
        print(f"poll failed: {e}", file=sys.stderr)
        return

    for item in pending.get("items", []):
        session_id = item["metadata"]["session_id"]
        try:
            claim = _api_request(
                api_url, token, "POST",
                f"/opbeta/outposts/devins/{session_id}/claim",
                {"acceptor_id": ACCEPTOR_ID},
            )
        except urllib.error.HTTPError as e:
            if e.code == 409:
                continue  # someone else claimed it first
            print(f"[{session_id}] claim failed: {e}", file=sys.stderr)
            continue

        deadline = claim.get("status", {}).get("claim_deadline")
        print(f"[{session_id}] claimed, claim_deadline={deadline}, dispatching")
        run_session.spawn(session_id)


if __name__ == "__main__":
    # one-time (or whenever you change sidecar_image) step: build + publish
    # the sidecar image under a name, so `modal deploy` and run_session can
    # both just reference it by name without ever rebuilding it themselves.
    # https://modal.com/docs/guide/images#named-images
    #
    # run this before the first `modal deploy pools/modal_local.py`:
    #   python3 pools/modal_local.py
    build_app = modal.App.lookup(f"outpost-pool-{POOL_NAME}-image-builds", create_if_missing=True)
    with modal.enable_output():
        sidecar_image.build(build_app).publish(SIDECAR_IMAGE_NAME)
    print(f"published {SIDECAR_IMAGE_NAME}")
